CREATE DATABASE DB_TESTEAPI
USE DB_TESTEAPI

CREATE TABLE TB_DADOS(
COD INT PRIMARY KEY IDENTITY(1,1),
USERID INT,
ID INT,
TITLE VARCHAR (100),
BODY VARCHAR(200)
)

CREATE PROCEDURE USP_CAD_DADOS
@USERID INT,
@ID INT,
@TITLE VARCHAR(100),
@BODY VARCHAR (200)

AS BEGIN 
	INSERT INTO TB_DADOS VALUES (@USERID, @ID, @TITLE, @BODY)
END


CREATE PROCEDURE USP_CONSU_DADOS
@COD INT

AS BEGIN 
	SELECT * FROM TB_DADOS WHERE COD = @COD
END



CREATE PROCEDURE USP_CONSU_TODOS_DADOS

AS BEGIN 
	SELECT COD AS 'Código', USERID AS 'User ID', ID, TITLE AS 'Title', BODY AS 'Body'   FROM TB_DADOS 
END


EXEC USP_CONSU_DADOS 1